name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      - name: Run linter
        working-directory: ./backend
        run: npm run lint || echo "Linter not configured, skipping..."
        continue-on-error: true

      - name: Run tests
        working-directory: ./backend
        run: npm test || echo "Tests not configured, skipping..."
        continue-on-error: true
        env:
          NODE_ENV: test

  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run linter
        working-directory: ./frontend
        run: npm run lint || echo "Linter not configured, skipping..."
        continue-on-error: true

      - name: Run tests
        working-directory: ./frontend
        run: npm test || echo "Tests not configured, skipping..."
        continue-on-error: true

